### ISSUE TITLE
set default argument value for add_zero_line()

### ISSUE THREAD

**Issue by knopfjt** [hdadvisors/hdatools#11]
@walkerke I think this is an easy one, but I'd like your recommended solution.

For the `add_zero_line()` theme helper function, I've set it up to add a darker line geometry fixed on zero for either the x- or y-axis, depending on user input.

```
add_zero_line <- function(axis = c("x", "y")) {

  if(axis == "x") {

    ggplot2::geom_vline(xintercept = 0, color = "#4b4f50", size = 0.5)

  } else {

    ggplot2::geom_hline(yintercept = 0, color = "#4b4f50", size = 0.5)

  }

}
```

So far it's pretty clear that nine times out of ten, our plots are using a continuous y-axis, so we add a zero line there. What is the best way to make "y" the default argument value so that adding `add_zero_line()` to the ggplot code -- without any argument supplied -- will default to that axis?

I know it only saves just a few seconds of typing, but I figure this is a good thing to know for the future.

Long term, I would like this functionality to be incorporated directly into each `theme_*()` function, like I was recently able to do for `flip_gridlines()` in https://github.com/hdadvisors/hdatools/commit/a21b7293b4721d6af9c2f7d12b4b5e165a03b20c. However, I'm not sure how to combine _both_ theme and geometry functions into a single function. That might be worth starting a new issue, since it unlocks a lot of other functionality.

**Comment by walkerke** [comment]
@knopfjt absolutely!  Here's how to do it.  To set a default argument from a vector of arguments (as you've supplied), you'll want the first element of the vector to be your default.  You'll then use the `match.arg()` function internally to set this value within the function (`rlang::arg_match()` also works the same way, with some bonus features).  `match.arg()` has the added benefit of restricting the possible argument values to only those available in the vector of arguments you've set.  So your function would now look like this:

```r
add_zero_line <- function(axis = c("y", "x")) {

  axis <- match.arg(axis)

  if(axis == "x") {

    ggplot2::geom_vline(xintercept = 0, color = "#4b4f50", size = 0.5)

  } else {

    ggplot2::geom_hline(yintercept = 0, color = "#4b4f50", size = 0.5)

  }

}
```

Here's how it then works:

```r
library(tidyverse)
library(hdatools)

set.seed(1983)
a <- rnorm(1000)
b <- rnorm(1000)
category <- sample(letters[1:4], 1000, replace = TRUE)

x <- tibble(a, b, category)

ggplot(x, aes(a, b, color = category)) + 
  geom_point() + 
  theme_hda() + 
  scale_color_hda() + 
  add_zero_line()
```
![image](https://user-images.githubusercontent.com/4872833/233471581-0b908f03-cd35-4027-b42f-56052a749e9b.png)

It's a pretty minor change so I'll just commit to the main branch if this looks OK with you, or I can do a PR for you to test.

**Comment by knopfjt** [comment]
@walkerke Perfect! Yes, please go ahead and commit to main.

**Comment by walkerke** [comment]
sounds good!
